apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- manage_role_binding.yaml

# Adds namespace to all resources.
namespace: authorino

patchesStrategicMerge:
- patches/setup_from_files_patch.yaml
