version: "3.7"
services:

  front-envoy:
    build:
      context: ./front-envoy
      dockerfile: Dockerfile
    environment:
      - FRONT_ENVOY_YAML
    networks:
      - envoymesh
    expose:
      - "8000"
      - "8001"
    ports:
      - "8000:8000"
      - "8001:8001"

  opa-service:
    image: openpolicyagent/opa:0.24.0-envoy
    volumes:
      - ./opa-service/policy.rego:/etc/policy.rego
      - ./opa-service/jwks.json:/etc/jwks.json
    command:
      - run
      - --log-level=debug
      - --server
      - --log-format=json-pretty
      - --set=plugins.envoy_ext_authz_grpc.addr=:9002
      - --set=decision_logs.console=true
      - /etc/policy.rego
      - jwks:/etc/jwks.json
    networks:
      envoymesh:
        aliases:
          - opa-service

  upstream-service:
    build:
      context: ./upstream-service
      dockerfile: Dockerfile
    networks:
      envoymesh:
        aliases:
          - upstream-service

networks:
  envoymesh: {}
