apiVersion: v1
kind: Service
metadata:
  name: oidc
  labels:
    app: authorino
spec:
  selector:
    app: authorino
    control-plane: controller-manager
  ports:
    - name: https
      port: 8083
      protocol: TCP
