apiVersion: config.authorino.3scale.net/v1beta1
kind: Service
metadata:
  name: echo-api
spec:
  hosts:
    - echo-api
  identity:
    - name: keycloak
      oidc:
        endpoint: http://keycloak:8080/auth/realms/ostia
  metadata:
    - userInfo:
        identitySource: keycloak
        credentialsRef:
          name: userinfosecret
    - uma:
        identitySource: keycloak
        credentialsRef:
          name: umacredentialssecret
  authorization:
    - OPAPolicy:
        uuid: 8fa79d93-0f93-4e23-8c2a-666be266cad1
        endpoint: http://opa:8181
        inlineRego: |
          allow {
            http_request.method == "GET"
            path = ["pets"]
          }

          allow {
            http_request.method == "GET"
            own_resource
          }

          allow {
            http_request.method == "GET"
            path = ["stats"]
            is_admin
          }

          own_resource {
            some petid
            path = ["pets", petid]
            resource := object.get(metadata, "uma", [])[0]
            owner := object.get(object.get(resource, "owner", {}), "id", "")
            subject := object.get(identity, "sub", object.get(identity, "username", ""))
            owner == subject
          }

          is_admin {
            identity.realm_access.roles[_] == "admin"
          }
    - JWTClaimSet:
        match:
          http:
            path: "/api/*"
        claim:
          aud: "api"
