echo-api:3000:
  enabled: true

  identity:
    - oidc:
        name: keycloak
        endpoint: http://keycloak:8080/auth/realms/ostia

  metadata:
    - userinfo:
        oidc: keycloak
        client_id: authorino
        client_secret: 2e5246f2-f4ef-4d55-8225-36e725071dee
    - uma:
        endpoint: http://keycloak:8080/auth/realms/ostia
        client_id: pets-api
        client_secret: 523b92b6-625d-4e1e-a313-77e7a8ae4e88

  authorization:
    - opa:
        uuid: 8fa79d93-0f93-4e23-8c2a-666be266cad1
        endpoint: 'http://opa:8181'
        rego: |
          allow {
            http_request.method == "GET"
            path = ["pets"]
          }

          allow {
            http_request.method == "GET"
            own_resource
          }

          allow {
            http_request.method == "GET"
            path = ["stats"]
            is_admin
          }

          own_resource {
            some petid
            path = ["pets", petid]
            resource := object.get(metadata, "uma", [])[0]
            owner := object.get(object.get(resource, "owner", {}), "id", "")
            subject := object.get(identity, "sub", object.get(identity, "username", ""))
            owner == subject
          }

          is_admin {
            identity.realm_access.roles[_] == "admin"
          }
    - jwt:
        enabled: false
        match:
          http:
            path: '/api/*'
        claim:
          aud: api
