apiVersion: config.authorino.3scale.net/v1beta1
kind: Service
metadata:
  name: echo-api
spec:
  hosts:
    - echo-api
  identity:
    - name: keycloak
      oidc:
        endpoint: http://keycloak:8080/auth/realms/ostia
      credentials:
        in: authorization_header
        key_selector: Bearer
  metadata:
    - name: userinfo
      userInfo:
        identitySource: keycloak
    - name: resource-data
      uma:
        endpoint: http://keycloak:8080/auth/realms/ostia
        credentialsRef:
          name: umacredentialssecret
  authorization:
    - name: my-main-policy
      opa:
        inlineRego: |
          allow {
            http_request.method == "GET"
            path = ["hello"]
          }

          allow {
            http_request.method == "GET"
            own_resource
          }

          allow {
            http_request.method == "GET"
            path = ["bye"]
            is_admin
          }

          own_resource {
            some greetingid
            path = ["greetings", greetingid]
            resource := object.get(metadata, "resource-data", [])[0]
            owner := object.get(object.get(resource, "owner", {}), "id", "")
            subject := object.get(identity, "sub", object.get(identity, "username", ""))
            owner == subject
          }

          is_admin {
            identity.realm_access.roles[_] == "admin"
          }
    - name: some-extra-rule
      json:
        rules:
          - selector: "auth.identity.email_verified"
            operator: eq
            value: "true"
          - selector: "context.source.address.Address.SocketAddress.address"
            operator: eq
            value: "127.0.0.1"
